---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repositories.yaml
  - nfs-storage.yaml
  - smb-storage.yaml
  - cloudflare-ddns.yaml
  - cert-manager.yaml
  - csi-driver-nfs-helmrelease.yaml
  - csi-driver-smb-helmrelease.yaml
  - cert-manager-helmrelease.yaml
  - reflector-helmrelease.yaml
